aws dynamodb "$@" --endpoint-url http://localhost:8000 delete-table --table-name 'test_user'
aws dynamodb "$@" --endpoint-url http://localhost:8000 delete-table --table-name 'test_recipe'
aws dynamodb "$@" --endpoint-url http://localhost:8000 delete-table --table-name 'test_batch'
aws dynamodb "$@" --endpoint-url http://localhost:8000 delete-table --table-name 'test_bottle'
aws dynamodb "$@" --endpoint-url http://localhost:8000 delete-table --table-name 'test_tester'
